-- Level 2 

-- 1. Write a SQL query to return the top 10 customers who have generated the most revenue for the store, including their names and total revenue generated.
select c.first_name, c.last_name, sum(p.amount) as total
from store s 
Join inventory i ON s.store_id = i.store_id
Join rental r ON r.inventory_id = i.inventory_id
Join payment p ON p.rental_id = r.rental_id
Join customer c On p.customer_id = c.customer_id
Group by p.customer_id
Order by total DESC Limit 10; 

-- 2. Write a SQL query to return the names and contact information of all customers who have rented films in all categories in the database.
SELECT 
    c.customer_id,
    c.first_name,
    c.last_name,
    c.email
FROM customer c
Join rental r ON c.customer_id = r.customer_id
Join inventory i ON r.inventory_id = i.inventory_id
Join film f ON i.film_id = f.film_id
Join film_category fc ON f.film_id = fc.film_id
group by c.customer_id
having COUNT(DISTINCT fc.category_id) = (select COUNT(*) from category);

-- 3. Write a SQL query to return the titles of all films in the database that have been rented at least once but never returned.

select distinct f.title 
from film f
Join inventory i on f.film_id = f.film_id
Join rental r on i.inventory_id = r.inventory_id
Where r.return_date is Null ; 


-- 4. Write a SQL query to return the names of all actors who have appeared in at least one film in each category in the database.

select a.first_name, a.last_name
from actor a
Join film_actor fa on a.actor_id = fa.actor_id
Join film f  on fa.film_id = f.film_id
Join film_category fc on f.film_id = fc.film_id
Join category c on fc.category_id = c.category_id
group by a.actor_id
having COUNT(DISTINCT fc.category_id) = (select COUNT(*) from category); 

-- 5. Write a SQL query to return the names of all customers who have rented the same film more than once in a single transaction, along with the number of times they rented it.

SELECT 
    c.first_name,
    c.last_name,
    f.title,
    COUNT(*) AS times
FROM rental r
JOIN customer c ON r.customer_id = c.customer_id
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film f ON i.film_id = f.film_id
GROUP BY c.customer_id, f.film_id, r.rental_date
HAVING COUNT(*) > 1;

-- 6. Write a SQL query to return the total revenue generated by each actor in the database, based on the rental fees of the films they have appeared in.
select a.first_name, a.last_name, sum(p.amount)
from actor a
Join film_actor fa on a.actor_id = fa.actor_id
Join film f  on fa.film_id = f.film_id
Join inventory i on i.film_id = f.film_id
Join rental r ON r.inventory_id = i.inventory_id
Join payment p ON p.rental_id = r.rental_id
group by a.actor_id;

-- 7. Write a SQL query to return the names of all actors who have appeared in at least one film with a rating of 'R', but have never appeared in a film with a rating of 'G'.
select a.first_name, a.last_name 
from actor a
Join film_actor fa on a.actor_id = fa.actor_id
Join film f  on fa.film_id = f.film_id
group by a.actor_id
Having sum(f.rating = 'R') > 0 and sum(f.rating = 'G') = 0 ; 


-- 8. Write a SQL query to return the titles of all films in the database that have been rented by more than 50 customers, but have never been rented by the same customer more than once.
select f.title 
from film f
Join inventory i on i.film_id = f.film_id
Join rental r on i.inventory_id = r.inventory_id
group by f.film_id, f.title
having count(DISTINCT r.customer_id ) > 50 and COUNT(*) = COUNT(DISTINCT r.customer_id);

-- 9. Write a SQL query to return the names of all customers who have rented a film from a category they have never rented from before.
SELECT 
	c.first_name, c.last_name
FROM customer c
Join rental r ON c.customer_id = r.customer_id
Join inventory i ON r.inventory_id = i.inventory_id
Join film f ON i.film_id = f.film_id
Join film_category fc on f.film_id = fc.film_id
Join category ca on fc.category_id = ca.category_id
where r.rental_date IN 
(
		SELECT MIN(r2.rental_date)
		FROM rental r2
		JOIN inventory i2 ON r2.inventory_id = i2.inventory_id
		JOIN film f2 ON i2.film_id = f2.film_id
		JOIN film_category fc2 ON f2.film_id = fc2.film_id
		WHERE r2.customer_id = c.customer_id
		AND fc2.category_id = ca.category_id
);



-- 10. Write a SQL query to return the titles of all films in the database that have been rented by every customer who has ever rented a film from the 'Action' category.
SELECT 
	f.title
FROM customer c
Join rental r ON c.customer_id = r.customer_id
Join inventory i ON r.inventory_id = i.inventory_id
Join film f ON i.film_id = f.film_id
Where r.customer_id in 
(
	select customer_id from (
		SELECT c1.customer_id
        from customer c1 
        Join rental r1 ON c1.customer_id = r1.customer_id
        Join inventory i1 ON r1.inventory_id = i1.inventory_id
		Join film f1 ON i1.film_id = f1.film_id
		Join film_category fc on f1.film_id = fc.film_id
		Join category c on fc.category_id = c.category_id
        where c.name = "Action"
    ) as t 
)

