use sakila;  
-- level 1

-- 1. 
Select first_name, last_name from actor; 

-- 2. 
select title, rental_rate, replacement_cost from sakila.film;

-- 3. 
SELECT f.film_id, f.title, COUNT(*) AS rental_count
FROM rental r
Join inventory i ON r.inventory_id = i.inventory_id
Join film f ON i.film_id = f.film_id
GROUP BY f.film_id, f.title
ORDER BY rental_count DESC
LIMIT 5;

-- 4. 
Select c.name , AVG(rental_duration) as duration_average
from film f
Join film_category fc ON f.film_id = fc.film_id
Join category c ON c.category_id = fc.category_id
Group by c.name; 

-- 5. 
Select c.first_name, c.last_name, a.address
from customer c 
Join address a ON c.address_id = a.address_id
Join rental r ON c.customer_id = r.customer_id
WHERE rental_date between '2022-01-01' AND '2022-01-31'; 

-- 6. Write a SQL query to return the revenue generated by each store in the database for the year 2021.
select s.store_id, SUM(amount) as sum
from store s 
Join inventory i ON s.store_id = i.store_id
Join rental r ON r.inventory_id = i.inventory_id
Join payment p ON p.rental_id = r.rental_id
Where rental_date between '2021-01-01' AND '2021-12-30'
Group by s.store_id; 

-- 7. Write a SQL query to return the names of all actors who have appeared in more than 20 films in the database.

select a.first_name, a.last_name, count(fa.film_id) as appear
from actor a
Join film_actor fa on a.actor_id = fa.actor_id
Join film f  on fa.film_id = f.film_id
group by a.actor_id
having COUNT(fa.film_id) > 20;

-- 8. Write a SQL query to return the titles of all films in the database that have a rating of 'PG-13' and a length of more than 120 minutes.
 
select * from film 
where film.length > 120 AND film.rating = 'PG-13'; 
